import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#ecbabc',
        'primary-fixed': '#ffdadb',
        'primary-fixed-dim': '#ecbabc',
        'primary-container': '#b28688',
        'on-primary': '#47272a',
        'on-primary-container': '#3f2123',
        'on-primary-fixed': '#2f1316',
        'on-primary-fixed-variant': '#603d3f',
        'inverse-primary': '#7b5456',
        'secondary': '#e9c176',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
        'secondary-container': '#604403',
        'on-secondary': '#412d00',
        'on-secondary-container': '#dab36a',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4201',
        'tertiary': '#c8c6c2',
        'tertiary-fixed': '#e5e2de',
        'tertiary-fixed-dim': '#c8c6c2',
        'tertiary-container': '#92908d',
        'on-tertiary': '#31302e',
        'on-tertiary-container': '#2a2a27',
        'on-tertiary-fixed': '#1c1c1a',
        'on-tertiary-fixed-variant': '#474744',
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-variant': '#353535',
        'surface-container': '#20201f',
        'surface-container-low': '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'surface-container-lowest': '#0e0e0e',
        'surface-tint': '#ecbabc',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d4c2c2',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'outline': '#9d8d8d',
        'outline-variant': '#504444',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        serif: ['Newsreader', 'Georgia', 'serif'],
        body: ['Manrope', 'sans-serif'],
        headline: ['Newsreader', 'serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        'lg': '0px',
        'xl': '0px',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}

export default config
